services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${APP_PORT:-8080}:80
            - ${VITE_PORT:-5173}:5173

        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/var/www/html
            - ./php_xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        # deploy:
        #     resources:
        #         limits:
        #             cpus: '0.50'
        #             memory: 50M
        #         reservations:
        #             cpus: '0.25'
        #             memory: 20M

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: php artisan queue:work
        volumes:
            - .:/var/www/html
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M

    redis:
        image: redis
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M

    mysql:
        image: mariadb
        environment:
            MARIADB_USERNAME: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
        volumes:
            - mysql-data:/var/lib

volumes:
    mysql-data:
