services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80
            - 5173:5173

        volumes:
            - .:/var/www/html

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: php artisan queue:work
        volumes:
            - .:/var/www/html

    redis:
        image: redis

    mysql:
        image: mariadb
        environment:
            MARIADB_USERNAME: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
        volumes:
            - mysql-data:/var/lib

volumes:
    mysql-data:
